on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up any environment or dependencies you need
      - name: Set up environment
        run: |
          # Add any setup commands here, if required

      # Your build step (e.g., running tests, building code, etc.)
      - name: Build project
        run: |
          # Add your build or test commands here, e.g., make, npm, etc.
      
      # Upload artifact step
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: path/to/your/artifacts