name: Deploy Blog to GitHub Pages

on:
  push:
    branches:
      - main  # or 'master' if that's your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload Static Files
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./  # or specify subfolder if your blog is inside one

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4